### ISSUE TITLE
Watch for dependent workspace crates

### ISSUE THREAD

**Issue by dmtrKovalenko** [lencx/vite-plugin-rsw#18]
**Is your feature request related to a problem? Please describe.**
Right now when I have a create that depends on some other crate 

```toml
# My wasm Cargo.toml
# ... 

[dependencies]
wasm-bindgen = "0.2.74"
lazy_static = "1.4.0"
console_error_panic_hook = "0.1.6"
# these 3 are local dependencies
rumotion-core = { path = "../../rumotion-core" }
video = { path = "../../video" }
svgr-macro = { path = "../../svgr-macro" }
```

rsw does not watch for file changes in dependent files. Only watches the original crate (https://github.com/lencx/vite-plugin-rsw/blob/main/src/compiler.ts#L164)

**Describe the solution you'd like**
RSW should parse the `crate`'s `Cargo.toml` for dependencies that are local (have path attribute) and also watch subdirectories. 

**Describe alternatives you've considered**
No alternatives :) 

**Additional context**
I am working on fixing this for my own workflow, can make a PR if you are interested.
